//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS_Latam_cashApplicationTool.Models.DBErrors
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASH_APPLICATION___Errors
    {
        public int id { get; set; }
        public string Guid_User { get; set; }
        public string Window { get; set; }
        public string Date_error { get; set; }
        public string Descrip_error { get; set; }
    }
}
