//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS_Latam_cashApplicationTool.Models.DBHistoricalInputUsers
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASH_APPLICATION___Historical_Input_Users
    {
        public int id { get; set; }
        public string Company_Code { get; set; }
        public Nullable<decimal> Alt_Payer { get; set; }
        public Nullable<decimal> Account { get; set; }
        public string Customer_Name { get; set; }
        public string Document_Type { get; set; }
        public string Document_Type_Description { get; set; }
        public Nullable<decimal> Amount_in_doc_curr { get; set; }
        public string Document_currency { get; set; }
        public Nullable<decimal> Document_Number { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> Document_Date { get; set; }
        public Nullable<System.DateTime> Baseline_Payment_Dte { get; set; }
        public Nullable<System.DateTime> Net_due_date { get; set; }
        public Nullable<decimal> Arrears_for_discount_1 { get; set; }
        public Nullable<decimal> Amount_in_local_currency { get; set; }
        public string Local_Currency { get; set; }
        public string Text_SAP { get; set; }
        public string Receipt_Number { get; set; }
        public Nullable<decimal> Dispute_Amount { get; set; }
        public string Reason_Code { get; set; }
        public Nullable<decimal> Agreement { get; set; }
        public string Description_Agreement { get; set; }
        public string ID_Doc_Number { get; set; }
        public string Entry_date_CAT { get; set; }
        public string GUID_Users { get; set; }
        public string Users_name { get; set; }
        public Nullable<decimal> Doc_Number_CAT { get; set; }
        public string Tool { get; set; }
        public string Status_ { get; set; }
        public string Posting_Date_SAP { get; set; }
        public Nullable<decimal> Document_number_SAP { get; set; }
    }
}
