//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS_Latam_cashApplicationTool.Models.DBUsersActivity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASH_APPLICATION___Users_Activity
    {
        public int id { get; set; }
        public string users_id { get; set; }
        public string users_names { get; set; }
        public string users_area { get; set; }
        public string users_status { get; set; }
        public string usersDatetime_login { get; set; }
        public string usersDatetime_logout { get; set; }
        public string usersClose_window { get; set; }
    }
}
