//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS_Latam_cashApplicationTool.Models.DBHistoricalDocNumbers
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASH_APPLICATION___Historical_Document_Numbers
    {
        public int id { get; set; }
        public string Company_Code { get; set; }
        public Nullable<decimal> Alt_Payer { get; set; }
        public Nullable<decimal> Account { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<decimal> Amnt_Cust_Payment { get; set; }
        public Nullable<decimal> Amnt_Invoices { get; set; }
        public Nullable<decimal> Amnt_Disputes { get; set; }
        public Nullable<decimal> Amnt_Cred_Notes { get; set; }
        public Nullable<decimal> Amnt_Cred_Balance { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public string Guid_User { get; set; }
        public string users_name { get; set; }
        public string entry_date_CAT { get; set; }
        public Nullable<int> Doc_Number_CAT { get; set; }
    }
}
