//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS_Latam_cashApplicationTool.Models.DBConctact
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASH_APPLICATION___Contacto_DHL
    {
        public string Whatsapp { get; set; }
        public string Mail_HelpDesk { get; set; }
    }
}
