//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFS_Latam_cashApplicationTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASH_APPLICATION___Users_Desktop_App
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string password { get; set; }
    }
}
